
* Version 2023.12.19

** Multiverse

Added the concept of a multiverse to the store. The main reason was so
you can set up more complex data schemas with references across
stores.

** Code Refactor

There use to be a lot of different methods to add, remove and persist
stuff in naive store. This has been cleaned up to have just a couple
of methods like add-multiverse-element. Have a look at the
deprecation.lisp files for each layer for the details of what has been
deprecated. We use cl-naive-deprecation to ease the transition, your
code should run without you having to change anything
immediately. Eventually you will have to update your code.

In general the code is cleaner and the interface simpler to learn.

** Speed

Did work on cleaning up speed bottle necks.

** Bugs

Many bugs where fixed during the conversion of the tests to cl-naive-tests.

** Tests

cl-naive-store now uses cl-naive-tests and the tests where rewritten
for better coverage and to be cleaner.

You will learn a lot from reading the test code.

[[file:home.org][Home]]
