* Bench Marks

You will have to load the speed test file manually to run the tests.

All the speed tests basically do is:

1. Inserts a lot (1 mil) of documents into a collection.
2. Persist the collection.
3. Clears the collection and reloads it from persisted file(s).
4. Repeats 1 to 3 with a lot more (usually x10) documents.

The tests will fail if expected time was exceeded for any task.

Expected time however is very dependant on what the specifications of
your computer are. Expected time in tests were doubled to try and
cater for variance but will most likely fail on anything that has less
than 16gb of ram. This does not mean that the database cannot be used
with less ram it just means that performance comes at a cost when
there is a lot of data.

Query time is not speed tested in these because it depends heavily on
the query. The moment you start using indexes queries are however very
fast, simple queries complete in fractions of a second.


#+BEGIN_SRC lisp

;;Load test-speed.lisp
(cl-naive-tests:run :suites :test-speed-simple)
;;or
;;Load test-indexed.lisp
(cl-naive-tests:run :suites :test-speed-indexed)
;;or
;;Load test-speed-naive-documents.lisp
(cl-naive-tests:run :suites :test-speed-naive-documents)
;;or
;;Load test-speed-sharding.lisp
(cl-naive-tests:run :suites :test-speed-sharding)

#+END_SRC

[[file:home.org][Home]]
