** Utils

Some utilities. More to come in the future.

*** [function] naive-document-to-sexp (document &key (versions-p t))

Converts a naive-documents:document to a sexp.

versions-p includes or excludes old versions of the document.

*** [function] naive-documents-to-sexps (documents)

Used to prepare docs to be sent over HTTP or shared with some other
system that does not have access to cl-naive-store.

*** [function] sexp-to-naive-document (multiverse sexp)

This function converts a sexp to a naive-documents:document. What it does not do is
sync the info with any existing documents in the collection. You will
have to do a perstist-document (or add-document if not a persisted
collection) on this document to sync with any existing documents in
the collection.

If you intend to use add-document just note that it does not sync any
child documents only persist-document does that as well. So if you are
not carefull you can end up with more than one document with the same
UUID and different values for child documents.

The function does check for existing-documents to at least make sure
that the same UUID is used and any child documents that do not have UUID's
already are supplied with UUIDs. Child documents that are reference
documents are also checked for consitent UUID.

The conversion is done on the assumption you have not trashed the document
beyond repair when you possibly hacked the sexp.

[[file:home.org][Home]] :noexport: [[file:implementor-api.org][Previous]] :noexport: [[file:tests.org][Next]] :noexport:
